name: Build the project code
on:
  workflow_call:
    secrets:
      HEX_ORGANIZATION_COINGAMING_KEY:
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.3" # Define the elixir version
          otp-version: "25.1" # Define the OTP version

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Restore Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: v2-release-${{ hashFiles('mix.lock') }}-${{ github.sha }}

          restore-keys: |
            v2-release-${{ hashFiles('mix.lock') }}-${{ github.sha }}
          path: |
            ~/.mix
            ./test/support/generated
            ./deps
            ./_build

      - name: Get deps and protobuf escript
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix hex.organization auth coingaming --key ${{secrets.HEX_ORGANIZATION_COINGAMING_KEY}}
          mix deps.get
          mix escript.install hex protobuf 0.10.0 --force
          echo "$HOME/.mix/escripts" >> $GITHUB_PATH

      - name: Generate test proto files
        if: steps.cache.outputs.cache-hit != 'true'
        run: scripts/gen-test-proto.sh

      - name: Compile dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Compile and chack warnings
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix compile --warnings-as-errors

