name: Build the project code
on:
  workflow_call:
    inputs:
      cache_paths:
        type: string
        required: false
        default: ""
      elixir-version:
        type: string
        required: false
        default: "1.14.3" # Define the elixir version
      otp-version:
        type: string
        required: false
        default: "25.1" # Define the OTP version
      mix-env:
        type: string
        required: false
        default: test
    secrets:
      HEX_ORGANIZATION_COINGAMING_KEY:
        required: true
      SSH_KEYS:
        required: false
      OBAN_FINGERPRINT:
        required: false
      OBAN_LICENSE_KEY:
        required: false

defaults:
  run:
    shell: bash

env:
  MIX_ENV: ${{ inputs.mix-env }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      OBAN_FINGERPRINT: ${{ secrets.OBAN_FINGERPRINT }}
      OBAN_LICENSE_KEY: ${{ secrets.OBAN_LICENSE_KEY }}

    steps:
      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          otp-version: ${{ inputs.otp-version }}

      - name: Install ExEnv
        run: mix archive.install hex ex_env 0.3.2 --force

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: SSH Deploy Keys Setup
        uses: cardoe/ssh-agent-deploy-key@v1
        with:
          ssh-private-key: |
            ${{ secrets.SSH_KEYS }}

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Restore Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: v2-release-${{ hashFiles('mix.lock') }}-${{ github.sha }}

          restore-keys: |
            v2-release-${{ hashFiles('mix.lock') }}-${{ github.sha }}
          path: |
            ${{ inputs.cache_paths }}
            ~/.mix
            ./deps
            ./_build

      - name: Add coingaming organization
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix hex.organization auth coingaming --key ${{secrets.HEX_ORGANIZATION_COINGAMING_KEY}}

      - name: Add oban repo
        if: steps.cache.outputs.cache-hit != 'true' && env.OBAN_FINGERPRINT
        run: mix hex.repo add oban https://getoban.pro/repo --fetch-public-key ${{env.OBAN_FINGERPRINT}} --auth-key ${{env.OBAN_LICENSE_KEY}}

      - name: Get deps and protobuf escript
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix escript.install hex protobuf 0.10.0 --force
          echo "$HOME/.mix/escripts" >> $GITHUB_PATH

      - name: Generate test proto files
        if: steps.cache.outputs.cache-hit != 'true'
        run: scripts/gen-test-proto.sh

      - name: Compile dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Download UAInspector DB
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix run --no-start -e "UAInspector.Downloader.download()"

      - name: Compile
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix compile
