name: Compile and check
on:
  workflow_call:
    inputs:
      cache_paths:
        type: string
        required: false
        default: ""
      elixir-version: 
        type: string
        required: false
        default: "1.14.3" # Define the elixir version
      otp-version:
        type: string
        required: false
        default: "25.1" # Define the OTP version
      mix-env: 
        type: string
        required: false
        default: test
    secrets:
      HEX_ORGANIZATION_COINGAMING_KEY:
        required: true

defaults:
  run:
    shell: bash
env:
  MIX_ENV: ${{ inputs.mix-env }}

jobs:
  build:
    name: Build
    uses: coingaming/.github/.github/workflows/build.yml@v1.1.0
    secrets: inherit
    with:
      mix-env: ${{ inputs.mix-env }}
      cache_paths: ${{ inputs.cache_paths }}
      elixir-version: ${{ inputs.elixir-version }}
      otp-version: ${{ inputs.otp-version }}


  code_checks:
    name: Run code checks
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Prepare repo and env
        uses: coingaming/.github/actions/prepare@v1.1.0
        with:
          mix-env: ${{ inputs.mix-env }}
          cache_paths: ${{ inputs.cache_paths }}
          elixir-version: ${{ inputs.elixir-version }}
          otp-version: ${{ inputs.otp-version }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Format
        run: mix format --check-formatted

      - name: Credo
        run: mix credo

      - name: Compile and chack warnings
        run: mix do clean, compile --warnings-as-errors

