name: Compile and check
on:
  workflow_call:
    inputs:
      cache_paths:
        type: string
        required: false
        default: ""
      elixir-version: 
        type: string
        required: false
        default: "1.14.3" # Define the elixir version
      otp-version:
        type: string
        required: false
        default: "25.1" # Define the OTP version
    secrets:
      HEX_ORGANIZATION_COINGAMING_KEY:
        required: true

defaults:
  run:
    shell: bash
env:
  MIX_ENV: test

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  code_checks:
    name: Run code checks
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ inputs.elixir-version }}
          otp-version: ${{ inputs.otp-version }}

      - name: Restore Cache
        uses: actions/cache@v2
        id: cache
        with:
          key: v2-release-${{ hashFiles('mix.lock') }}-${{ github.sha }}

          restore-keys: |
            v2-release-${{ hashFiles('mix.lock') }}-${{ github.sha }}
          path: |
            ${{ inputs.cache_paths }}
            ~/.mix
            ./deps
            ./_build

      - name: Compile and chack warnings
        run: mix do clean, compile --warnings-as-errors

      - name: Format
        run: mix format --check-formatted

      - name: Credo
        run: mix credo
