name: Compile and check
on:
  workflow_call:
    inputs:
      cache_paths:
        type: string
        required: false
        default: ""
      mix-env:
        type: string
        required: false
        default: test
      elixir-code-path:
        type: string
        required: false
        default: "."
    secrets:
      HEX_ORGANIZATION_COINGAMING_KEY:
        required: true

defaults:
  run:
    shell: bash

env:
  MIX_ENV: ${{ inputs.mix-env }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      mix-env: ${{ inputs.mix-env }}
      cache_paths: ${{ inputs.cache_paths }}
      elixir-code-path: ${{ inputs.elixir-code-path }}

  dialyzer:
    name: Run dialyzer
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Prepare repo and env
        uses: ./actions/prepare
        with:
          mix-env: ${{ inputs.mix-env }}
          cache_paths: ${{ inputs.cache_paths }}
          token: ${{ secrets.GH_TOKEN != '' && secrets.GH_TOKEN || github.token }}
          elixir-code-path: ${{ inputs.elixir-code-path }}

      - name: Run dialyzer
        run: |
          cd ${{ inputs.elixir-code-path }}
          mix dialyzer --format github
