name: Manual release to HEX
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      cache_paths:
        type: string
        required: false
        default: ""
      mix-env:
        type: string
        required: false
        default: test
      elixir-code-path:
        type: string
        required: false
        default: "."
    secrets:
      HEX_ORGANIZATION_COINGAMING_KEY:
        required: true

defaults:
  run:
    shell: bash

env:
  MIX_ENV: ${{ inputs.mix-env }}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      ref: ${{ inputs.version }}
      mix-env: ${{ inputs.mix-env }}
      cache_paths: ${{ inputs.cache_paths }}
      elixir-code-path: ${{ inputs.elixir-code-path }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: ${{ inputs.mix-env }}
      HEX_API_KEY: ${{ secrets.HEX_ORGANIZATION_COINGAMING_KEY }}
      VSN: ${{ inputs.version }}

    steps:
      - name: Prepare repo and env
        uses: ./actions/prepare
        with:
          ref: ${{ inputs.version }}
          mix-env: ${{ inputs.mix-env }}
          cache_paths: ${{ inputs.cache_paths }}
          token: ${{ secrets.GH_TOKEN != '' && secrets.GH_TOKEN || github.token }}
          elixir-code-path: ${{ inputs.elixir-code-path }}

      - name: Prepare VERSION file
        run: echo ${VSN:1} > VERSION

      - name: Force Hex Publish
        run: |
          cd ${{ inputs.elixir-code-path }}
          mix hex.publish --organization coingaming --yes
