name: Release to HEX
on:
  workflow_call:
    inputs:
      cache_paths:
        type: string
        required: false
        default: ""
      elixir-version: 
        type: string
        required: false
        default: "1.14.3" # Define the elixir version 
      otp-version: 
        type: string
        required: false
        default: "25.1" # Define the OTP version
      mix-env: 
        type: string
        required: false
        default: test
      package-dir:
        type: string
        required: false
        default: "./" # Directory containing the package. Useful for umbrella projects
    secrets:
      HEX_ORGANIZATION_COINGAMING_KEY:
        required: true
        
defaults:
  run:
    shell: bash

env:
  MIX_ENV: ${{ inputs.mix-env }}

jobs:
  build:
    name: Build
    uses: coingaming/.github/.github/workflows/build.yml@v1.1.0
    secrets: inherit
    with:
      mix-env: ${{ inputs.mix-env }}
      cache_paths: ${{ inputs.cache_paths }}
      elixir-version: ${{ inputs.elixir-version }}
      otp-version: ${{ inputs.otp-version }}

  release:
    name: Release
    needs: build
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: ${{ inputs.mix-env }}
      HEX_API_KEY: ${{ secrets.HEX_ORGANIZATION_COINGAMING_KEY }}

    steps:
      - name: Prepare repo and env
        uses: coingaming/.github/actions/prepare@v1.1.0
        with:
          mix-env: ${{ inputs.mix-env }}
          cache_paths: ${{ inputs.cache_paths }}
          elixir-version: ${{ inputs.elixir-version }}
          otp-version: ${{ inputs.otp-version }}
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0

      - name: Add NPM Registry
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Install Semantic Release
        run:  npm install semantic-release @semantic-release/git @semantic-release/exec @semantic-release/changelog @heathmont/semantic-release-elixir-hex

      - name: Semantic Release
        run:
          cd %{{ inputs.package-dir }} \
          npx semantic-release --extends @heathmont/semantic-release-elixir-hex
